baseURL = "https://beta.adaptpos.com/"
languageCode = "en-us"
title = "AdaptPOS - Android EMV Solutions & Gift Card Services"
googleAnalytics = ""

[params]
  Author = "Midnight Oil Systems, LLC"
  Description = "The official website for the AdaptPOS.  Midnight Oil Systems, LLC d.b.a AdaptPOS is located in Denver, CO and services the USA, Canada, Mexico and other countries."

  twitter = "AdaptPOS"
  facebook = "AdaptPOS"

  enableRSS = true
  enableTOC = false

  enableSummary = true
  useDescriptionReplaceSummary = true

  enableGoogleAnalytics = true

  customCss = [ "/css/site.css" ]
  customJs = []

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "rounded"

[params.nav]
  "AdaptPAY" = "/adaptpay/"
  "Android EMV Devices" = "/emv-devices/"
  "Gift Cards" = "/adaptgift/"
  "Q & A" = "/company/faq/"
  
[social]
  facebook = "https://www.facebook.com/adaptpos"
  twitter = "https://www.twitter.com/adaptpos"
  github = "https://www.github.com/adaptpos"

